image: maven:3-openjdk-8

stages:
  - verification 
  - compile
  - test
  - deploy



verification_job:
  stage: verification
  script:
    - 'pwd'
    - 'ls -l'
    - 'mvn --version'
    - 'java -version'
    - 'javac -version'

compile_job:

  stage: compile
  script:
    - 'mvn compile'

verify_job:
  stage: test
  script:
    - 'mvn test'
 

deploy:
  stage: deploy
  script:
    - echo "Deploying to GitLab Maven Repository Coming Soon"
    - 'mvn deploy'